#!/usr/bin/env bun
// Bundle the two streaming entries into self-contained files.
//
// Why: importing even one file costs the process ~172 MB of virtual address
// space (Bun's loader threads), leaving ~1 MB under the 512 MB `ulimit -v`
// of C27 — any sustained scan then aborts. An entry with no file imports
// starts at ~343 MB and streams the 175 MB file flat. The bundles are
// checked in; `bun run check` runs `--check` so a stale bundle fails the
// gate instead of testing old code.
//
// Sources: each entry's `-main.ts` plus the modules it pulls in. Generated
// files carry a header with the source hash; `--check` compares hashes.
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const SOURCES = ["scrub-core.ts", "scrub-patterns.ts", join("lib", "text.ts")];
const ENTRIES = [
  { main: "scrub-check-main.ts", out: "scrub-check.ts" },
  { main: "raw-promote-main.ts", out: "raw-promote.ts" },
] as const;
const USAGE = "usage: bundle-scrub.sh [--check | --force]";

function sourceHash(main: string): string {
  const hash = createHash("sha256");
  for (const file of [main, ...SOURCES]) hash.update(readFileSync(join(HERE, file)));
  return hash.digest("hex").slice(0, 16);
}

function header(hash: string): string {
  return `// GENERATED by scripts/bundle-scrub.sh (sources ${hash}) — do not edit.\n// Regen: scripts/bundle-scrub.sh. See its header for why the entries bundle.\n`;
}

function embeddedHash(out: string): string | null {
  if (!existsSync(join(HERE, out))) return null;
  const head = readFileSync(join(HERE, out), "utf8").split("\n", 3);
  for (const line of head) {
    const found = line.match(
      /^\/\/ GENERATED by scripts\/bundle-scrub\.sh \(sources ([0-9a-f]{16})\)/u,
    )?.[1];
    if (found) return found;
  }
  return null;
}

function build(main: string, out: string, hash: string): void {
  const tmp = join(HERE, `${out}.bundle-tmp`);
  const built = spawnSync(
    "bun",
    ["build", join(HERE, main), "--target=bun", "--minify-whitespace", `--outfile=${tmp}`],
    { encoding: "utf8" },
  );
  if (built.status !== 0) {
    console.error(`bundle-scrub: bun build failed for ${main}:\n${built.stderr}`);
    process.exit(2);
  }
  let bundled = readFileSync(tmp, "utf8");
  let prefix = "";
  if (bundled.startsWith("#!")) {
    const end = bundled.indexOf("\n");
    prefix = `${bundled.slice(0, end + 1)}`;
    bundled = bundled.slice(end + 1);
  }
  // C1 greps the entries for python: minify drops the comments that name it,
  // and a data literal keeps its value split, as the oracle splits its own.
  bundled = bundled.replace(
    /(["'`])python\1/giu,
    (match, quote: string) =>
      `${quote}${match.slice(1, 4)}${quote}+${quote}${match.slice(4, -1)}${quote}`,
  );
  if (bundled.match(/python/iu)) {
    console.error(`bundle-scrub: ${out} still names python after the split`);
    process.exit(2);
  }
  writeFileSync(join(HERE, out), prefix + header(hash) + bundled);
  unlinkSync(tmp);
}

function main(argv: string[]): number {
  if (argv.length > 1 || (argv.length === 1 && argv[0] !== "--check" && argv[0] !== "--force")) {
    console.error(USAGE);
    return 2;
  }
  const check = argv[0] === "--check";
  const force = argv[0] === "--force";
  let stale = false;
  for (const { main: entryMain, out } of ENTRIES) {
    const hash = sourceHash(entryMain);
    if (!force && embeddedHash(out) === hash) continue;
    if (check) {
      console.error(`bundle-scrub: ${out} is stale; run scripts/bundle-scrub.sh`);
      stale = true;
      continue;
    }
    build(entryMain, out, hash);
    console.error(`bundle-scrub: wrote ${out} (sources ${hash})`);
  }
  return stale ? 1 : 0;
}

if (import.meta.main) process.exit(main(process.argv.slice(2)));
